### PR TITLE
[FEATURE] about tnp page

### PR DESCRIPTION
**Pull request by Rahilsiddique**
#23  done

### CODE REVIEW

**Comment by riyavishwa981** [comment]
When you make the screen small keep the title and information at top and the image below. Also change the information return under TNP 
Also change StaffFoto to StaffPhoto (since it should be understood by others as well)
Keep the space minimum between the image and contact us

**Comment by riyavishwa981** [comment]
Reduce the height of the image beside to align it with contact us, its okay if the gap between them becomes more
Also when you make the screen small keep the title and information at top and the image below.
image

**Review by riyavishwa981 — APPROVED** [review]

**Comment by JayeshVP24** [comment]
ok few things.

- [ ] rename pages/aboutTNP.astro -> pages/aboutTnP.astro
- [ ] delete components/About/TNPabout.astro -> move that code directly into pages/aboutTnP.astro
- [ ] rename div tag title About TNP -> h1 tag title with text "About TCET - Training & Placement Cell"
- [ ] increase line height of description below title _hint: use leading class of tailwindCSS_
- [ ]  change src of image -> "/Testimonials/{ur code}" _no need to mention public folder, u can use relative path of public directly by slash `/` _
- [ ] the image in staff has rouneded borders. make sure of this.
- [ ] remove border color, the default border color of tailwindCSS works for us
- [ ] change bg to `gray-200` or `gray-100` whichever seems nice. use tailwind defaults
- [ ] change expertise color to `text-slate-600`
- [ ] expertise badge width should be full `w-full`
- [ ] do check the contact page in figma, it is not accurate. you forgot borders and placeholder text properly
- [ ] in contact too. rename colors from custom to tailwind Defaults. such as `text-slate-600 bg-slate-100 or bg-slate-50`
- [ ] email placeholder should have underline. _hint: tailwindclass placeholder:underline_
- [ ] submit button background - `bg-blue-600` and keep text site `text-base`
- [ ] the image in contact section has no rounded borders, remove them
- [ ] give proper space between label and text box

**Comment by Rahilsiddique** [comment]
ok few things.

- [x] rename pages/aboutTNP.astro -> pages/aboutTnP.astro
- [x] delete components/About/TNPabout.astro -> move that code directly into pages/aboutTnP.astro
- [ ] rename div tag title About TNP -> h1 tag title with text "About TCET - Training & Placement Cell"
- [x] increase line height of description below title _hint: use leading class of tailwindCSS_
- [x]  change src of image -> "/Testimonials/{ur code}" _no need to mention public folder, u can use relative path of public directly by slash `/` _
- [x] the image in staff has rouneded borders. make sure of this.
- [x] remove border color, the default border color of tailwindCSS works for us
- [x] change bg to `gray-200` or `gray-100` whichever seems nice. use tailwind defaults
- [x] change expertise color to `text-slate-600`
- [x] expertise badge width should be full `w-full`
- [x] do check the contact page in figma, it is not accurate. you forgot borders and placeholder text properly
- [x] in contact too. rename colors from custom to tailwind Defaults. such as `text-slate-600 bg-slate-100 or bg-slate-50`
- [x] email placeholder should have underline. _hint: tailwindclass placeholder:underline_
- [x] submit button background - `bg-blue-600` and keep text site `text-base`
- [x] the image in contact section has no rounded borders, remove them
- [x] give proper space between label and text box

**Pull request merged**
